platform :ios, '7.0'

target 'YuePaoBa' do
    pod 'AFNetworking','~> 2.6.1'
    pod 'Masonry', '~> 0.6.3'
    pod 'SDWebImage', '3.7.3'
    pod 'OpenSSL', '~> 1.0.204.1'
    pod 'Aspects','~>1.4.1'
    pod 'BlocksKit', '~> 2.2.5'
    pod 'TSMessages', '~> 0.9.12'
    pod 'UIImage-Helpers', '~> 0.0.3'
    pod 'TPKeyboardAvoiding', '~> 1.2.10'
    pod 'ActionSheetPicker-3.0', '~> 2.0.3'
    pod 'SFHFKeychainUtils', '~> 0.0.1'
    pod 'MJRefresh', '~> 2.4.12'
    pod 'UITextView+Placeholder', '~> 1.1.0'
    pod 'Realm', '~> 0.98.5'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'GPUImage', '~> 0.1.7'
    pod 'HMSegmentedControl', '~> 1.5.2'
    pod 'DACircularProgress', '~> 2.3.1'
end